// Generated by https://quicktype.io

export interface TopLevel {
  products: Product[];
  monthly_sales: MonthlySale[];
}

export interface MonthlySale {
  month: string;
  sales: Sale[];
}

export interface Sale {
  product_id: number;
  quantity: number;
}

export interface Product {
  name: string;
  price: number;
  stock: number;
}
